### ISSUE TITLE
New project can't load C++/CUDA extensions

### ISSUE THREAD

**Issue by qsthhm** [elevencupoftea/ps_sd#2]
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
Python 3.10.11 (you have 3.10.12)
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
Memory-efficient attention, SwiGLU, sparse and more won't be available.
Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by elevencupoftea** [comment]
xfromers removed the beta package, so now the stable version is used, which works with 2.1.0+cu121. I have updated the install.sh, so do a clean install again.

**Comment by elevencupoftea** [comment]
I also added the XFORMERS parameter to notebook. Сhange the value if you will experience difficulties with xformers in the future. Generation will be slightly slower

**Comment by qsthhm** [comment]
Solved! very detailed answer. Thank you for having you.
